// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/moonbucks.proto

package moonbucks

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Size int32

const (
	Size_SMALL  Size = 0
	Size_MEDIUM Size = 1
	Size_LARGE  Size = 2
)

var Size_name = map[int32]string{
	0: "SMALL",
	1: "MEDIUM",
	2: "LARGE",
}

var Size_value = map[string]int32{
	"SMALL":  0,
	"MEDIUM": 1,
	"LARGE":  2,
}

func (x Size) String() string {
	return proto.EnumName(Size_name, int32(x))
}

func (Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0ec415dbe409406, []int{0}
}

type GetOrderRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ec415dbe409406, []int{0}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateOrderRequest struct {
	Size                 Size     `protobuf:"varint,2,opt,name=size,proto3,enum=moonbucks.Size" json:"size,omitempty"`
	CoffeeType           string   `protobuf:"bytes,3,opt,name=coffee_type,json=coffeeType,proto3" json:"coffee_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ec415dbe409406, []int{1}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetSize() Size {
	if m != nil {
		return m.Size
	}
	return Size_SMALL
}

func (m *CreateOrderRequest) GetCoffeeType() string {
	if m != nil {
		return m.CoffeeType
	}
	return ""
}

type UpdateOrderRequest struct {
	Order                *CoffeeOrder          `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	OrderMask            *field_mask.FieldMask `protobuf:"bytes,2,opt,name=order_mask,json=orderMask,proto3" json:"order_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateOrderRequest) Reset()         { *m = UpdateOrderRequest{} }
func (m *UpdateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderRequest) ProtoMessage()    {}
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ec415dbe409406, []int{2}
}

func (m *UpdateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderRequest.Unmarshal(m, b)
}
func (m *UpdateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderRequest.Merge(m, src)
}
func (m *UpdateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderRequest.Size(m)
}
func (m *UpdateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderRequest proto.InternalMessageInfo

func (m *UpdateOrderRequest) GetOrder() *CoffeeOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *UpdateOrderRequest) GetOrderMask() *field_mask.FieldMask {
	if m != nil {
		return m.OrderMask
	}
	return nil
}

type CoffeeOrder struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 Size     `protobuf:"varint,2,opt,name=size,proto3,enum=moonbucks.Size" json:"size,omitempty"`
	CoffeeType           string   `protobuf:"bytes,3,opt,name=coffee_type,json=coffeeType,proto3" json:"coffee_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoffeeOrder) Reset()         { *m = CoffeeOrder{} }
func (m *CoffeeOrder) String() string { return proto.CompactTextString(m) }
func (*CoffeeOrder) ProtoMessage()    {}
func (*CoffeeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ec415dbe409406, []int{3}
}

func (m *CoffeeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoffeeOrder.Unmarshal(m, b)
}
func (m *CoffeeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoffeeOrder.Marshal(b, m, deterministic)
}
func (m *CoffeeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoffeeOrder.Merge(m, src)
}
func (m *CoffeeOrder) XXX_Size() int {
	return xxx_messageInfo_CoffeeOrder.Size(m)
}
func (m *CoffeeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_CoffeeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_CoffeeOrder proto.InternalMessageInfo

func (m *CoffeeOrder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CoffeeOrder) GetSize() Size {
	if m != nil {
		return m.Size
	}
	return Size_SMALL
}

func (m *CoffeeOrder) GetCoffeeType() string {
	if m != nil {
		return m.CoffeeType
	}
	return ""
}

func init() {
	proto.RegisterEnum("moonbucks.Size", Size_name, Size_value)
	proto.RegisterType((*GetOrderRequest)(nil), "moonbucks.GetOrderRequest")
	proto.RegisterType((*CreateOrderRequest)(nil), "moonbucks.CreateOrderRequest")
	proto.RegisterType((*UpdateOrderRequest)(nil), "moonbucks.UpdateOrderRequest")
	proto.RegisterType((*CoffeeOrder)(nil), "moonbucks.CoffeeOrder")
}

func init() { proto.RegisterFile("protos/moonbucks.proto", fileDescriptor_e0ec415dbe409406) }

var fileDescriptor_e0ec415dbe409406 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xcf, 0xae, 0xd2, 0x40,
	0x14, 0xc6, 0x6d, 0xef, 0x9f, 0xd8, 0x53, 0x73, 0x8b, 0x93, 0x70, 0x25, 0x8d, 0x7f, 0x6a, 0x75,
	0xd1, 0xdc, 0x98, 0x36, 0xd6, 0x95, 0xec, 0x10, 0x91, 0x98, 0xd0, 0x98, 0x14, 0x89, 0x89, 0x2e,
	0x48, 0x69, 0x4f, 0xc9, 0x08, 0x74, 0x6a, 0xa7, 0x90, 0x80, 0x61, 0xe3, 0x2b, 0xf8, 0x16, 0xae,
	0x7c, 0x17, 0x5f, 0xc1, 0x07, 0x31, 0x9d, 0x82, 0x14, 0x08, 0xbb, 0xbb, 0x62, 0x38, 0xf3, 0xcd,
	0xaf, 0xdf, 0x77, 0x3e, 0xb8, 0x4e, 0x33, 0x96, 0x33, 0xee, 0xcc, 0x18, 0x4b, 0x46, 0xf3, 0x70,
	0xc2, 0x6d, 0x31, 0x20, 0xca, 0xff, 0x81, 0x6e, 0x8c, 0x19, 0x1b, 0x4f, 0xd1, 0x11, 0x17, 0xa3,
	0x79, 0xec, 0xc4, 0x14, 0xa7, 0xd1, 0x70, 0x16, 0xf0, 0x49, 0x29, 0xd6, 0x1f, 0x6e, 0x14, 0x41,
	0x4a, 0x9d, 0x20, 0x49, 0x58, 0x1e, 0xe4, 0x94, 0x25, 0x1b, 0x94, 0xf9, 0x14, 0xb4, 0x2e, 0xe6,
	0x1f, 0xb2, 0x08, 0x33, 0x1f, 0xbf, 0xcd, 0x91, 0xe7, 0xe4, 0x0a, 0x64, 0x1a, 0x35, 0x24, 0x43,
	0xb2, 0xce, 0x7c, 0x99, 0x46, 0xe6, 0x67, 0x20, 0xed, 0x0c, 0x83, 0x1c, 0xf7, 0x54, 0xcf, 0xe0,
	0x9c, 0xd3, 0x15, 0x36, 0x64, 0x43, 0xb2, 0xae, 0x5c, 0xcd, 0xde, 0x79, 0xec, 0xd3, 0x15, 0xfa,
	0xe2, 0x92, 0x3c, 0x01, 0x35, 0x64, 0x71, 0x8c, 0x38, 0xcc, 0x97, 0x29, 0x36, 0xce, 0x0c, 0xc9,
	0x52, 0x7c, 0x28, 0x47, 0x1f, 0x97, 0x29, 0x9a, 0x6b, 0x20, 0x83, 0x34, 0x3a, 0x64, 0xbf, 0x80,
	0x0b, 0x56, 0xfc, 0x17, 0x26, 0x54, 0xf7, 0xba, 0x02, 0x6f, 0x8b, 0xb7, 0xa5, 0xba, 0x14, 0x91,
	0xd7, 0x00, 0xe2, 0x20, 0x42, 0x0b, 0x3f, 0xaa, 0xab, 0xdb, 0x65, 0x6a, 0x7b, 0xbb, 0x17, 0xfb,
	0x5d, 0xb1, 0x17, 0x2f, 0xe0, 0x13, 0x5f, 0x11, 0xea, 0xe2, 0x68, 0x86, 0xa0, 0x56, 0x80, 0x87,
	0xc9, 0x6f, 0x27, 0xe3, 0x8d, 0x05, 0xe7, 0x85, 0x9c, 0x28, 0x70, 0xd1, 0xf7, 0x5a, 0xbd, 0x5e,
	0xed, 0x0e, 0x01, 0xb8, 0xf4, 0x3a, 0x6f, 0xdf, 0x0f, 0xbc, 0x9a, 0x54, 0x8c, 0x7b, 0x2d, 0xbf,
	0xdb, 0xa9, 0xc9, 0xee, 0x6f, 0x19, 0xee, 0x09, 0x27, 0x7d, 0xcc, 0x16, 0x34, 0x44, 0xf2, 0x09,
	0xee, 0x6e, 0xdb, 0x21, 0x7a, 0xe5, 0xf3, 0x07, 0x95, 0xe9, 0x27, 0x36, 0x64, 0x3e, 0xf8, 0xf1,
	0xe7, 0xef, 0x4f, 0xf9, 0x3e, 0xd1, 0x9c, 0xc5, 0x4b, 0x47, 0xc4, 0xe6, 0xce, 0x77, 0x1a, 0xad,
	0xc9, 0x17, 0x50, 0x2b, 0x9d, 0x92, 0x47, 0xd5, 0xf7, 0x47, 0x5d, 0x9f, 0xc4, 0xd7, 0x05, 0x5e,
	0x33, 0x61, 0x87, 0x6f, 0x4a, 0x37, 0xe4, 0x2b, 0xa8, 0x95, 0x52, 0xf7, 0xe0, 0xc7, 0x65, 0x9f,
	0x84, 0x3f, 0x17, 0xf0, 0xc7, 0x6e, 0xbd, 0xea, 0x5d, 0xfc, 0xda, 0x34, 0x5a, 0x37, 0xcb, 0xf2,
	0xdf, 0xd4, 0x7f, 0xc9, 0xc4, 0xdb, 0xd5, 0x52, 0xee, 0x8d, 0x8f, 0x2e, 0x45, 0xef, 0xaf, 0xfe,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x34, 0x08, 0xc8, 0x58, 0x42, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*CoffeeOrder, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CoffeeOrder, error)
	UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*CoffeeOrder, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*CoffeeOrder, error) {
	out := new(CoffeeOrder)
	err := c.cc.Invoke(ctx, "/moonbucks.OrderService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CoffeeOrder, error) {
	out := new(CoffeeOrder)
	err := c.cc.Invoke(ctx, "/moonbucks.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*CoffeeOrder, error) {
	out := new(CoffeeOrder)
	err := c.cc.Invoke(ctx, "/moonbucks.OrderService/UpdateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	GetOrder(context.Context, *GetOrderRequest) (*CoffeeOrder, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CoffeeOrder, error)
	UpdateOrder(context.Context, *UpdateOrderRequest) (*CoffeeOrder, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) GetOrder(ctx context.Context, req *GetOrderRequest) (*CoffeeOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CoffeeOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderServiceServer) UpdateOrder(ctx context.Context, req *UpdateOrderRequest) (*CoffeeOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moonbucks.OrderService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moonbucks.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moonbucks.OrderService/UpdateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateOrder(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moonbucks.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _OrderService_GetOrder_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _OrderService_UpdateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/moonbucks.proto",
}
